name: Build Apache HTTP Server for s390x

on:
  push:
    branches:
      - trunk
  workflow_dispatch:

jobs:
  build:
      runs-on: ubuntu-20.04

      strategy:
        matrix:
          os: [ubuntu-20.04]

      steps:            
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up build environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essentials git python openssl gcc autoconf make libtool-bin libpcre3-dev libxml2  libexpat1 libexpat1-dev wget tar
          sudo apt-get install -y crossbuild-essential-s390x

      - name: Build Apache HTTP Server
        run: |
          git clone https://github.com/apache/httpd.git
          cd httpd
          ./buildconf
          CC="s390x-linux-gnu-gcc" ./configure --host=s390x-linux-gnu --with-mpm=prefork
          make
